version: '{build}'  
image: Visual Studio 2019 Preview
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
before_build:
    - cmd: dotnet --version
build_script:  
- ps: .\Build.ps1
test: off
after_build:
    - 7z a -tzip BlackVueDownloader.zip .\BlackVueDownloader\artifacts
artifacts:  
- path: BlackVueDownloader.zip
  name: BlackVueDownloader
deploy:
  release: 'v1.1.$(appveyor_build_version)'
  description: 'Release v1.1.$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: +L7awVOpkoS9AFH2iw1R84aEas7eGSFoR1MmKz285Svi8M2H3cSZ8h47bG9NRenw
  artifact: BlackVueDownloader
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
